spring:
  application:
    name: spring-security-test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_test?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 20010121
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true